### ISSUE TITLE
In transifex, we have "froide-2" and "froide" for Finnish. Which one do we need, can the second one be deleted?

### ISSUE THREAD

**Issue by jaakkokorhonen** [stefanw/froide#142]

**Comment by jaakkokorhonen** [comment]
In transifex, we have "froide-2" and "froide" for Finnish. Which one do we need, can the second one be deleted?

**Comment by TomiToivio** [comment]
Yes, we had a bit of trouble since some people were translating "froide" and some were translating "froide-2".

https://www.transifex.com/projects/p/froide/

https://www.transifex.com/projects/p/froide-2/

I imported the Finnish "froide-2" files into "froide" so now "froide" should be the one that is more up-to-date... I hope...

**Comment by stefanw** [comment]
`froide` is the correct one. `froide-2` is not maintained.

Transifex has changed URL structures since we started using it, very confusing.
