### ISSUE TITLE
Country names are blanked out

### ISSUE THREAD

**Issue by GiantCrocodile** [stefanw/froide#199]
When I try to refer to laws in Germany and I use the phrase 'Bundesrepublik Deutschland' the word Deutschland is blanked out because it is interpreted as a part of an address. We should fine a solution so we can define what info is sensitive and which isn't to remove false positives.

**Comment by stefanw** [comment]
You have "Deutschland" as part of your address and all parts of an address are automatically redacted as they are always considered private. It doesn't always make sense, but we rather err on the side of caution. Usually legibility is not significantly impaired. In severe cases individual messages can always be fixed by moderators.

If you have a concrete suggestion for a solution, please reopen.
